import React, { ReactNode } from "react";
import Header from "./Header";
import Head from "next/head";
import Footer from './Footer';
import CssBaseline from "@mui/material/CssBaseline";
import { Box } from "@mui/material";

type Props = {
    children?: ReactNode;
};

export default function Layout({ children }: Props) {
    return (
        <React.Fragment>
            <Head>
                <title>Real Estate</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-32x32.png" sizes="32x32" />
            </Head>
            <CssBaseline />
            <Box id="back-to-top-anchor" />
            <Header />
            {children}
            <Footer />
        </React.Fragment>
    );
}
